// Compiles design-system/project/tokens.json into src/styles/tokens.css (the same
// custom properties the design system page generates).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(fs.readFileSync(path.join(here, '../../design-system/project/tokens.json'), 'utf8'));
const themes = tokens.color.themes.map((t) => t.id);
const first = themes[0];
const pick = (v, th) => (typeof v === 'string' ? v : v[th] ?? v[first]);
const color = (v) => v.replace(/^\{(.+)\}$/, 'var(--$1)');

let css = '/* Generated by scripts/tokens-css.mjs from design-system/project/tokens.json. Do not edit. */\n';
const themed = (th) =>
  tokens.color.tokens.map((t) => `  --${t.name}: ${color(pick(t.value, th))};`).join('\n') + '\n' +
  tokens.shadow.tokens.map((t) => `  --${t.name}: ${pick(t.value, th)};`).join('\n');
css += `:root, [data-theme="${first}"] {\n${themed(first)}\n}\n`;
for (const th of themes.slice(1)) css += `[data-theme="${th}"] {\n${themed(th)}\n}\n`;
const flat = Object.entries(tokens)
  .filter(([k, v]) => !['color', 'type', 'shadow'].includes(k) && v && Array.isArray(v.tokens))
  .flatMap(([, v]) => v.tokens);
css += ':root {\n' + flat.map((t) => `  --${t.name}: ${t.value};`).join('\n') + '\n' +
  Object.entries(tokens.type.families).map(([k, v]) => `  --font-${k}: ${v};`).join('\n') + '\n}\n';

const out = path.join(here, '../src/styles/tokens.css');
fs.writeFileSync(out, css);
console.log('wrote', path.relative(process.cwd(), out));
